### PR TITLE
Created cocoa pod, updates test, minor cleanup

### PR DESCRIPTION
**Pull request by orkoden**
I added a `podspec` file to support using PunyCode-Cocoa with [cocoa pods](cocoapods.org). While doing that, I separated the library code more from the example project. The unit testing framework was changed to the more current XCTest and some compiler flags were changed to the ones recommend by XCode. No changes were made to the source code.

The podspec currently points to my fork on github and includes my e-mail. If you'd rather have yours there and have control over the pod, [you can claim it](https://trunk.cocoapods.org/claims/new). I had to integrate this quickly with a project, so I just went ahead.

### CODE REVIEW

**Comment by Wevah** [comment]
Thanks! I'll check this out in a bit.

**Comment by Wevah** [comment]
Looks good to me.

**Comment by Wevah** [comment]
I filed a claim for the pod, so you might get bugged about it. Thanks!

**Comment by orta** [comment]
:rainbow:

**Comment by orkoden** [comment]
:smile:

**Comment by Wevah** [comment]
I have no idea what I'm doing re: pods but I'll figure it out!

**Pull request merged**
